
default:
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 1
l1-org-hwd-lh:
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L1-Intro-Org-LH.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 2
l2-flat:
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

lab1-cuda:
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l3-pipe:
	pdflatex L3-InOrderPipe.tex
	pdflatex L3-InOrderPipe.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

