
default:
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 1
l1-org-hwd-lh:
	pdflatex L1-Intro-Org-LH.tex
	pdflatex L1-Intro-Org-LH.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 2
l2-flat:
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

lab1-cuda:
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l3-pipe:
	pdflatex L3-InOrderPipe.tex
	pdflatex L3-InOrderPipe.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l4-vliw:
	pdflatex L4-VLIW.tex
	pdflatex L4-VLIW.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l5-loop:
	pdflatex L5-LoopParI.tex
	pdflatex L5-LoopParI.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l6-mem:
	pdflatex L6-MemIntro.tex
	pdflatex L6-MemIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l7-net:
	pdflatex L7-Interconnect.tex
	pdflatex L7-Interconnect.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l8-loc:
	pdflatex L8-LocOfRef.tex
	pdflatex L8-LocOfRef.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l9-tomasulo:
	pdflatex L9-OoOproc.tex
	pdflatex L9-OoOproc.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l10-tls:
	pdflatex L10-tls.tex
	pdflatex L10-tls.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

proj:
	pdflatex ProjectDiscussion.tex
	pdflatex ProjectDiscussion.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

