
default:
	pdflatex Intro.tex
	pdflatex Intro.tex
	pdflatex Processor.tex
	pdflatex Processor.tex
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	pdflatex MemHierarchy.tex
	pdflatex MemHierarchy.tex
	pdflatex Interconnect.tex
	pdflatex Interconnect.tex
	pdflatex MemSeqCons.tex
	pdflatex MemSeqCons.tex
	pdflatex ListHom.tex
	pdflatex ListHom.tex
	pdflatex Assignm1and2.tex
	pdflatex Assignm1and2.tex
	pdflatex LoopParI.tex
	pdflatex LoopParI.tex
	pdflatex LocOfRef.tex
	pdflatex LocOfRef.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 1
intro:
	pdflatex Intro.tex
	pdflatex Intro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 2
listhom:
	pdflatex ListHom.tex
	pdflatex ListHom.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 3
processor:
	pdflatex Processor.tex
	pdflatex Processor.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 4
vliw:
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

assignm:
	pdflatex Assignm1and2.tex
	pdflatex Assignm1and2.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb
# Lecture 5
mem:
	pdflatex MemHierarchy.tex
	pdflatex MemHierarchy.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 7
interconnect:
	pdflatex Interconnect.tex
	pdflatex Interconnect.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 9
seqcons:
	pdflatex MemSeqCons.tex
	pdflatex MemSeqCons.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

looppar:
	pdflatex LoopParI.tex
	pdflatex LoopParI.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

locref:
	pdflatex LocOfRef.tex
	pdflatex LocOfRef.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

