
default:
	pdflatex Processor.tex
	pdflatex Processor.tex
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

processor:
	pdflatex Processor.tex
	pdflatex Processor.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

vliw:
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

