
default:
	pdflatex Processor.tex
	pdflatex Processor.tex
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	pdflatex MemHierarchy.tex
	pdflatex MemHierarchy.tex
	pdflatex Interconnect.tex
	pdflatex Interconnect.tex
	pdflatex MemSeqCons.tex
	pdflatex MemSeqCons.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

processor:
	pdflatex Processor.tex
	pdflatex Processor.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

vliw:
	pdflatex VLIW.tex
	pdflatex VLIW.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

mem:
	pdflatex MemHierarchy.tex
	pdflatex MemHierarchy.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

interconnect:
	pdflatex Interconnect.tex
	pdflatex Interconnect.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

seqcons:
	pdflatex MemSeqCons.tex
	pdflatex MemSeqCons.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

