
default:
	pdflatex Interpreter.tex
	pdflatex Interpreter.tex
	pdflatex TypeChecking.tex
	pdflatex TypeChecking.tex
	pdflatex IntermCode.tex
	pdflatex IntermCode.tex
	pdflatex MachineCode.tex
	pdflatex MachineCode.tex
	pdflatex RegAlloc.tex
	pdflatex RegAlloc.tex
	pdflatex Functions.tex
	pdflatex Functions.tex
	pdflatex OptimTAC.tex
	pdflatex OptimTAC.tex
	pdflatex Optim2.tex
	pdflatex Optim2.tex
	pdflatex ParTeaser.tex
	pdflatex ParTeaser.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

interpret:
	pdflatex Interpreter.tex
	pdflatex Interpreter.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

typecheck:
	pdflatex TypeChecking.tex
	pdflatex TypeChecking.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

intermcode:
	pdflatex IntermCode.tex
	pdflatex IntermCode.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

machinecode:
	pdflatex MachineCode.tex
	pdflatex MachineCode.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

regalloc:
	pdflatex RegAlloc.tex
	pdflatex RegAlloc.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

functions:
	pdflatex Functions.tex
	pdflatex Functions.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

tacoptim:
	pdflatex OptimTAC.tex
	pdflatex OptimTAC.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

otheroptim:
	pdflatex Optim2.tex
	pdflatex Optim2.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

parteaser:
	pdflatex ParTeaser.tex
	pdflatex ParTeaser.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

