
default:
	pdflatex L1-Intro-LH.tex
	pdflatex L1-Intro-LH.tex
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	pdflatex L3-InOrderPipe.tex
	pdflatex L3-InOrderPipe.tex
#	pdflatex Processor.tex
#	pdflatex Processor.tex
#	pdflatex VLIW.tex
#	pdflatex VLIW.tex
#	pdflatex MemHierarchy.tex
#	pdflatex MemHierarchy.tex
#	pdflatex Interconnect.tex
#	pdflatex Interconnect.tex
#	pdflatex MemSeqCons.tex
#	pdflatex MemSeqCons.tex
#	pdflatex Assignm1and2.tex
#	pdflatex Assignm1and2.tex
#	pdflatex LoopParI.tex
#	pdflatex LoopParI.tex
#	pdflatex LocOfRef.tex
#	pdflatex LocOfRef.tex
#	pdflatex Project.tex
#	pdflatex Project.tex
#	pdflatex OoOproc.tex
#	pdflatex OoOproc.tex
#	pdflatex TLS.tex
#	pdflatex TLS.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 1
l1-intro:
	pdflatex L1-Intro-LH.tex
	pdflatex L1-Intro-LH.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 2
l2-listhom:
	pdflatex L2-Flatenning.tex
	pdflatex L2-Flatenning.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

lab1-cuda:
	pdflatex Lab1-CudaIntro.tex
	pdflatex Lab1-CudaIntro.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

l3-proc:
	pdflatex L3-InOrderPipe.tex
	pdflatex L3-InOrderPipe.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

# Lecture 3
#processor:
#	pdflatex Processor.tex
#	pdflatex Processor.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 4
#vliw:
#	pdflatex VLIW.tex
#	pdflatex VLIW.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#assignm:
#	pdflatex Assignm1and2.tex
#	pdflatex Assignm1and2.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 5
#mem:
#	pdflatex MemHierarchy.tex
#	pdflatex MemHierarchy.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 7
#interconnect:
#	pdflatex Interconnect.tex
#	pdflatex Interconnect.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

# Lecture 9
#seqcons:
#	pdflatex MemSeqCons.tex
#	pdflatex MemSeqCons.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#looppar:
#	pdflatex LoopParI.tex
#	pdflatex LoopParI.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#locref:
#	pdflatex LocOfRef.tex
#	pdflatex LocOfRef.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#proj:
#	pdflatex Project.tex
#	pdflatex Project.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#ooo:
#	pdflatex OoOproc.tex
#	pdflatex OoOproc.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

#tls:
#	pdflatex TLS.tex
#	pdflatex TLS.tex
#	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

